spring:
  application:
    name: auth-service

server:
  port: 9081

management:
  endpoints:
    web:
      exposure:
        include: "*"

bank:
  security:
    jwt:
      issuer: banking-transaction-engine
      audience: banking-clients
      secret: ${JWT_SECRET}
      access-token-expiration: 900000
      refresh-token-expiration: 604800000
