bank:
  security:
    jwt:
      issuer: banking-transaction-engine
      audience: banking-clients
      secret: qVYGbrfWw6+03VwPCCLk/BJ/75etRP8Sepop+I+lMmA=
      access-token-expiration: 900000
      refresh-token-expiration: 604800000