package com.bank.security.authorization;

public enum Permission {

    ACCOUNT_CREATE,
    ACCOUNT_READ,
    ACCOUNT_UPDATE,
    ACCOUNT_DELETE,

    CUSTOMER_CREATE,
    CUSTOMER_READ,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,

    TRANSACTION_CREATE,
    TRANSACTION_READ,
    TRANSACTION_APPROVE,
    TRANSACTION_CANCEL,

    USER_CREATE,
    USER_READ,
    USER_UPDATE,
    USER_DELETE,

    ROLE_ASSIGN,
    PERMISSION_ASSIGN,

    AUDIT_READ,

    REPORT_READ,
    REPORT_EXPORT,

    SYSTEM_CONFIGURATION

}